name: Run Cypress tests inside Docker

on:
  push:
    branches:
      - default
  pull_request:
    branches:
      - default

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Ensure public/index.html exists
        run: |
          if [ ! -f public/index.html ]; then
            echo "public/index.html does not exist. Creating..."
            mkdir -p public
            echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title></head><body><div id="root"></div></body></html>' > public/index.html
          fi

      - name: Install react-scripts
        run: npm install react-scripts

      - name: Run Cypress tests inside Docker
        uses: cypress-io/github-action@v2
        with:
          build: true
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          config-file: cypress.config.js

